// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: internal/credit_card/api/grpchandlers/proto/credit_card.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostCreditCardCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Number    string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	ExpiresAt string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CvvCode   string `protobuf:"bytes,4,opt,name=cvv_code,json=cvvCode,proto3" json:"cvv_code,omitempty"`
	PinCode   string `protobuf:"bytes,5,opt,name=pin_code,json=pinCode,proto3" json:"pin_code,omitempty"`
}

func (x *PostCreditCardCredentialsRequest) Reset() {
	*x = PostCreditCardCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostCreditCardCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCreditCardCredentialsRequest) ProtoMessage() {}

func (x *PostCreditCardCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCreditCardCredentialsRequest.ProtoReflect.Descriptor instead.
func (*PostCreditCardCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescGZIP(), []int{0}
}

func (x *PostCreditCardCredentialsRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PostCreditCardCredentialsRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *PostCreditCardCredentialsRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PostCreditCardCredentialsRequest) GetCvvCode() string {
	if x != nil {
		return x.CvvCode
	}
	return ""
}

func (x *PostCreditCardCredentialsRequest) GetPinCode() string {
	if x != nil {
		return x.PinCode
	}
	return ""
}

type PostCreditCardCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostCreditCardCredentialsResponse) Reset() {
	*x = PostCreditCardCredentialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostCreditCardCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCreditCardCredentialsResponse) ProtoMessage() {}

func (x *PostCreditCardCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCreditCardCredentialsResponse.ProtoReflect.Descriptor instead.
func (*PostCreditCardCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescGZIP(), []int{1}
}

var File_internal_credit_card_api_grpchandlers_proto_credit_card_proto protoreflect.FileDescriptor

var file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x20, 0x50, 0x6f, 0x73, 0x74, 0x43,
	0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x76, 0x76, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x76, 0x76, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x23, 0x0a, 0x21,
	0x50, 0x6f, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x7c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x61,
	0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x27, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43,
	0x61, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73,
	0x6d, 0x6b, 0x64, 0x65, 0x6e, 0x69, 0x73, 0x2f, 0x79, 0x61, 0x70, 0x2d, 0x69, 0x6e, 0x66, 0x6f,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescOnce sync.Once
	file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescData = file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDesc
)

func file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescGZIP() []byte {
	file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescOnce.Do(func() {
		file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescData)
	})
	return file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDescData
}

var file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_goTypes = []interface{}{
	(*PostCreditCardCredentialsRequest)(nil),  // 0: proto.PostCreditCardCredentialsRequest
	(*PostCreditCardCredentialsResponse)(nil), // 1: proto.PostCreditCardCredentialsResponse
}
var file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_depIdxs = []int32{
	0, // 0: proto.CreditCardService.PostSaveCreditCard:input_type -> proto.PostCreditCardCredentialsRequest
	1, // 1: proto.CreditCardService.PostSaveCreditCard:output_type -> proto.PostCreditCardCredentialsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_init() }
func file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_init() {
	if File_internal_credit_card_api_grpchandlers_proto_credit_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostCreditCardCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostCreditCardCredentialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_goTypes,
		DependencyIndexes: file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_depIdxs,
		MessageInfos:      file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_msgTypes,
	}.Build()
	File_internal_credit_card_api_grpchandlers_proto_credit_card_proto = out.File
	file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_rawDesc = nil
	file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_goTypes = nil
	file_internal_credit_card_api_grpchandlers_proto_credit_card_proto_depIdxs = nil
}
